# This is a basic workflow to help you get started with Actions

name: Check Code Format

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # Install packages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort black pylint
          
      # Check code format
      - name: Lint
        run: |
          flake8 --max-line-length 88 joeynmt test/unit
          isort --profile black --check-only joeynmt test/unit
          pylint --rcfile=.pylintrc joeynmt test/unit
          black --check --line-length 88 --target-version py39 joeynmt test/unit
          
      # Run unittest
      - name: Test
        run: |
          python -m pytest
  
